"""Trained style LoRA registry.

Each adapter is a directory under settings.loras_dir:

    loras/<id>/lora.safetensors   — the trained weights
    loras/<id>/lora.json          — metadata (name, trigger word, base, …)

The directory scan is cheap (a handful of small JSON files), so the registry is
stateless and reads the disk on every call — no cache to invalidate when a
training job installs a new style.
"""

from __future__ import annotations

import json
import logging
import re
import shutil
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)

WEIGHTS_FILENAME = "lora.safetensors"
META_FILENAME = "lora.json"

# Trigger words are baked into captions and prompts verbatim — keep them plain
# tokens so they survive tokenization and shell/JSON round-trips unambiguously.
TRIGGER_RE = re.compile(r"^[A-Za-z0-9_]{2,30}$")


@dataclass(frozen=True)
class LoraStyleInfo:
    id: str
    name: str
    trigger: str
    base: str  # engine family the adapter applies to ("wan-5b")
    created_at: datetime
    weights_path: Path


def _slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug[:40] or "style"


class LoraRegistry:
    def __init__(self, loras_dir: Path) -> None:
        self._dir = loras_dir

    def list(self) -> list[LoraStyleInfo]:
        if not self._dir.is_dir():
            return []
        styles = []
        for entry in sorted(self._dir.iterdir()):
            info = self._read(entry)
            if info is not None:
                styles.append(info)
        styles.sort(key=lambda s: s.created_at, reverse=True)
        return styles

    def get(self, lora_id: str) -> LoraStyleInfo | None:
        # ids are generated by _slugify + hex suffix, but guard against path
        # tricks anyway since the id arrives from a form field.
        if not lora_id or Path(lora_id).name != lora_id:
            return None
        return self._read(self._dir / lora_id)

    def install(
        self,
        weights: Path,
        *,
        name: str,
        trigger: str,
        base: str = "wan-5b",
        steps: int | None = None,
        image_count: int | None = None,
    ) -> LoraStyleInfo:
        """Copy trained weights into the registry and write their metadata."""
        lora_id = f"{_slugify(name)}-{uuid.uuid4().hex[:6]}"
        target_dir = self._dir / lora_id
        target_dir.mkdir(parents=True, exist_ok=False)
        shutil.copyfile(weights, target_dir / WEIGHTS_FILENAME)
        created_at = datetime.now(timezone.utc)
        meta = {
            "id": lora_id,
            "name": name,
            "trigger": trigger,
            "base": base,
            "steps": steps,
            "image_count": image_count,
            "created_at": created_at.isoformat(),
        }
        (target_dir / META_FILENAME).write_text(
            json.dumps(meta, indent=2), encoding="utf-8"
        )
        log.info("style installed", extra={"lora_id": lora_id, "style": name})
        return LoraStyleInfo(
            id=lora_id,
            name=name,
            trigger=trigger,
            base=base,
            created_at=created_at,
            weights_path=target_dir / WEIGHTS_FILENAME,
        )

    def delete(self, lora_id: str) -> bool:
        info = self.get(lora_id)
        if info is None:
            return False
        shutil.rmtree(self._dir / lora_id)
        log.info("style deleted", extra={"lora_id": lora_id})
        return True

    def _read(self, entry: Path) -> LoraStyleInfo | None:
        meta_path = entry / META_FILENAME
        weights_path = entry / WEIGHTS_FILENAME
        if not (meta_path.is_file() and weights_path.is_file()):
            return None
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            return LoraStyleInfo(
                id=meta["id"],
                name=meta["name"],
                trigger=meta["trigger"],
                base=meta.get("base", "wan-5b"),
                created_at=datetime.fromisoformat(meta["created_at"]),
                weights_path=weights_path,
            )
        except (json.JSONDecodeError, KeyError, ValueError):
            log.warning("skipping unreadable style metadata", extra={"path": str(meta_path)})
            return None
